class Dictionary:
    def __init__(self):
        self.diccionare = [
        [
            {"name": "esperanza", "definition": "Confianza en que algo deseado suceda."},
            {"name": "silencio", "definition": "Ausencia de ruido."},
            {"name": "cultura", "definition": "Conjunto de conocimientos y creencias compartidos."},
            {"name": "sabiduría", "definition": "Conocimiento profundo y reflexivo."},
            {"name": "historia", "definition": "Relato de acontecimientos pasados."},
            {"name": "libertad", "definition": "Estado de no estar sometido."},
            {"name": "honor", "definition": "Valor moral que implica respeto."},
            {"name": "verdad", "definition": "Conformidad de lo que se dice con la realidad."},
            {"name": "conocimiento", "definition": "Información adquirida o entendimiento."},
            {"name": "empatía", "definition": "Capacidad de comprender los sentimientos de otros."},
            {"name": "justicia", "definition": "Principio moral que busca la equidad."},
            {"name": "identidad", "definition": "Conjunto de características que definen a una persona."},
            {"name": "solidaridad", "definition": "Apoyo mutuo entre individuos."},
            {"name": "compasión", "definition": "Sentimiento de empatía hacia el sufrimiento ajeno."},
            {"name": "lealtad", "definition": "Fidelidad a una persona o causa."},
            {"name": "tolerancia", "definition": "Aceptación de ideas o prácticas diferentes."},
            {"name": "responsabilidad", "definition": "Compromiso de asumir las consecuencias de las acciones."},
            {"name": "coherencia", "definition": "Conformidad y consistencia entre ideas y acciones."},
            {"name": "generosidad", "definition": "Disposición a dar y compartir recursos."},
            {"name": "optimismo", "definition": "Actistud positiva ante la vida."},
        ],
        [
            {"name": "interacción", "definition": "Acción que ocurre entre dos o más elementos."},
            {"name": "nostalgia", "definition": "Sentimiento de tristeza por el pasado."},
            {"name": "comunicación", "definition": "Proceso de intercambio de información."},
            {"name": "resiliencia", "definition": "Capacidad de adaptarse a situaciones adversas."},
            {"name": "identidad", "definition": "Características que definen a un individuo o grupo."},
            {"name": "justicia", "definition": "Principio moral que busca la equidad y el respeto."},
            {"name": "perspectiva", "definition": "Punto de vista desde el cual se observa algo."},
            {"name": "influencia", "definition": "Capacidad de afectar o cambiar a otros."},
            {"name": "transformación", "definition": "Cambio significativo en la forma o naturaleza de algo."},
            {"name": "sabiduría colectiva", "definition": "Conocimiento compartido por un grupo."},
            {"name": "creatividad", "definition": "Capacidad de generar ideas originales."},
            {"name": "sostenibilidad", "definition": "Capacidad de mantener un equilibrio en los recursos."},
            {"name": "diversidad", "definition": "Variedad de elementos dentro de un grupo."},
            {"name": "autenticidad", "definition": "Veracidad y originalidad en las acciones."},
            {"name": "compromiso", "definition": "Obligación de cumplir con una causa o propósito."},
            {"name": "colaboración", "definition": "Trabajo conjunto para lograr un objetivo."},
            {"name": "innovación", "definition": "Introducción de ideas o métodos nuevos."},
            {"name": "desarrollo", "definition": "Progreso y mejora en un contexto determinado."},
            {"name": "empoderamiento", "definition": "Proceso de aumentar la confianza en uno mismo."},
            {"name": "conexión", "definition": "Relación que se establece entre dos o más elementos."},
        ],
        [
            {"name": "conexión", "definition": "Relación que permite la interacción entre elementos."},
            {"name": "paradoja", "definition": "Situación que presenta contradicciones evidentes."},
            {"name": "epistemología", "definition": "Estudio del conocimiento y su naturaleza."},
            {"name": "utopía", "definition": "Sociedad ideal que representa un estado de perfección."},
            {"name": "cognición", "definition": "Proceso mental de adquisición de conocimiento."},
            {"name": "axiología", "definition": "Estudio de los valores y su influencia."},
            {"name": "antropocentrismo", "definition": "Perspectiva que considera al ser humano como centro."},
            {"name": "dialéctica", "definition": "Método de argumentación que busca la verdad."},
            {"name": "existencialismo", "definition": "Filosofía que enfatiza la libertad individual."},
            {"name": "interseccionalidad", "definition": "Análisis de cómo diferentes opresiones se cruzan."},
            {"name": "neurociencia", "definition": "Estudio del sistema nervioso y el cerebro."},
            {"name": "sociología", "definition": "Estudio de las sociedades y sus interacciones."},
            {"name": "psicología", "definition": "Estudio del comportamiento humano y los procesos mentales."},
            {"name": "filosofía", "definition": "Reflexión crítica sobre la existencia y el conocimiento."},
            {"name": "metafísica", "definition": "Estudio de la naturaleza de la realidad."},
            {"name": "teoría del caos", "definition": "Estudio de sistemas complejos e impredecibles."},
            {"name": "cibernética", "definition": "Estudio de sistemas automáticos y su control."},
            {"name": "semiótica", "definition": "Estudio de los signos y su significado."},
            {"name": "metacognición", "definition": "Reflexión sobre los propios procesos de pensamiento."},
            {"name": "fenomenología", "definition": "Estudio de la experiencia y la conciencia."},
        ],
            [
            {"name": "multiculturalismo", "definition": "Reconocimiento de diversas culturas en una sociedad."},
            {"name": "metacognición", "definition": "Reflexión sobre los propios procesos mentales."},
            {"name": "ontología", "definition": "Estudio del ser y de la existencia."},
            {"name": "hermenéutica", "definition": "Teoría de la interpretación de textos."},
            {"name": "deconstrucción", "definition": "Método crítico que busca analizar conceptos."},
            {"name": "teoría del caos", "definition": "Estudio de sistemas complejos e impredecibles."},
            {"name": "sociopolítica", "definition": "Análisis de las relaciones entre sociedad y política."},
            {"name": "ciberespacio", "definition": "Entorno virtual creado por la interconexión digital."},
            {"name": "sostenibilidad", "definition": "Capacidad de mantener el equilibrio en los recursos."},
            {"name": "paradigma", "definition": "Modelo o conjunto de creencias que guía el pensamiento."},
            {"name": "epistemología crítica", "definition": "Estudio crítico de la naturaleza del conocimiento."},
            {"name": "biopoder", "definition": "Control sobre la vida y los cuerpos."},
            {"name": "posmodernismo", "definition": "Corriente cultural y filosófica que cuestiona las narrativas."},
            {"name": "cosmopolitismo", "definition": "Ideología que promueve la unidad global."},
            {"name": "neocolonialismo", "definition": "Dominación indirecta de una nación sobre otra."},
            {"name": "ciberfeminismo", "definition": "Feminismo en el contexto digital."},
            {"name": "transhumanismo", "definition": "Movimento por la evolución del ser humano."},
            {"name": "postestructuralismo", "definition": "Rechazo de estructuras fijas en el análisis."},
            {"name": "bioética", "definition": "Ética en las ciencias biológicas y médicas."},
            {"name": "antropología", "definition": "Estudio de la humanidad y sus culturas."},
        ]
    ]
